#!/usr/bin/env bash
source config
for arg in "$@";do
  case $arg in
      -r|--rclone) clone="rclone"; shift ;;
      -l|--lclone) clone="lclone"; shift ;;
      -g|--gclone) clone="gclone"; shift ;;
      -c|--copy)   action="copy" ; shift ;;
      -m|--move)   action="move" ; shift ;;
      -s|--sync)   action="sync" ; shift ;;
      -a|--auto)   auto=true     ; shift ;;
      -t|--test)   test="echo "  ; shift ;;
      -d|--dest)   dest_="$2"    ; shift 2 ;;
      -f|--flag)   flags+=" $2 " ; shift 2 ;;
      -z|--shcut)  action="backend shortcut";shift ;;
      -u|--update) update=true   ; shift ;;
  esac
done
set_name="$1"
args="$@"
