#!/usr/bin/env bash
# syntax `./fcomp setname1 setname2` creates a differential file in src_folders
source config_init $@
set $args
outfile="$src_folders"/folders_in_"$1"_not_in_"$2"
comm -23 "$src_folders"/src_"$1" "$src_folders"/src_"$2" | tee $outfile

read -r -p "$action these folders? y/n " resp
if [ $resp != "y" ];then 
  echo "Exiting fcomp";exit
else 
  source listcopy "$outfile" "$1"
fi