#!/usr/bin/env bash
source config $@
>$src_all;>$src_dest_all

cat "$set_folder/$1" | while read src dest; do
  if [ ! -z "$src" ];then
    src_norm=`echo $src | sed -E 's/[^[:alnum:]]/_/g'`
    outfile="$src_folders/src_$src_norm";>$outfile
    echo -e "Creating list of source ($src) folders"
    rclone tree --noindent --noreport --full-path -d --filter-from filter "$src" |\
    sort|uniq|tee $outfile -a $src_all >/dev/null
    if [ ! -z "$dest" ];then
      echo -e "Creating list of source ($src) and dest ($dest) folders"
      cat $outfile | while read folder; do
        echo -e "$src$folder$IFS1$dest$folder" >> $src_dest_all
      done
    fi
    rm $outfile
  fi
done

for i in `ls $src_folders`;do sort -o "$src_folders/$i" "$src_folders/$i";done
for j in `ls $src_dest_folders`;do sort -o "$src_dest_folders/$j" "$src_dest_folders/$j";done
echo -e "`cat $src_all|wc -l` folders in $src_all set"
