#!/usr/bin/env bash

source config
infile="$src_folders/src_$1"
infile2="$src_dest_folders/src_dest_$1"
destroot=$2
shift 2

filter=`echo "$@" | sed -r 's/ /.*/g'`
src_list=`cat $infile | grep -i -E "$filter"`
echo -e "$src_list"
read -p "Copy these folders? y/n " resp
if [ $resp != "y" ];then exit;fi

cat $infile2 | grep -i -E "$filter" |\
while IFS=$IFS1 read src destdummy; do
  dest=$destroot/${src/*\//}
  echo -e "\nCopying files from source ( $src ) to destination ( $dest )"
  # echo -e "$clone copy $src $dest $flags"
  "$clone" copy "$src" "$dest" $flags
done
