#!/usr/bin/env bash

source config
infile="$src_folders/src_$1"
infile2="$src_dest_folders/src_dest_$1"
shift
filter=`echo "$@" | sed -r 's/ /.*/g'`
src_list=`cat $infile | grep -i -E "$filter"`
echo -e "$src_list"
read -p "Copy these folders? y/n " resp
if [ $resp != "y" ];then exit;fi

# copy_list=`cat $infile2 | grep -i -E "$filter"`
# echo "$copy_list" | while IFS=$IFS1 read src dest; do
cat $infile2 | grep -i -E "$filter" |\
while IFS=$IFS1 read src dest; do
  echo -e "\nCopying files from source to destination: $src $dest"
  echo -e "$clone copy $src $dest $flags"
  # "$clone" copy "$src" "$dest" $flags
done
