#!/usr/bin/env bash
# syntax: `./listshcut filter_file set_file` copies a shortcut of folders that match filters
# in filter_file from source to destination in the set_file
filter_file="$1"
shift
listcopy_args="$@"
while IFS= read -r filter;do
  source shcut -a "$listcopy_args" $filter
done <$filter_file